# Spine Switches
spine:
  defaults:
    platform: VEOS-LAB
    bgp_as: 65001
    # Overlay loopback IP and same pool can be assigned to both spine and l3leaf switches
    # If same loopback pool is defined for both spine and l3leaf,
    # < loopback_ipv4_offset > must be set in either one of the node_types
    loopback_ipv4_pool: 10.252.253.0/24
    # Recommended for vEOS
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
  nodes:
    eps01.tripeee.zone:
      id: 1
      mgmt_ip: 192.168.11.9/24
    eps02.tripeee.zone:
      id: 2
      mgmt_ip: 1192.168.11.10/24
    eps03.tripeee.zone:
      id: 13
      mgmt_ip: 192.168.11.11/24
    eps04.tripeee.zone:
      id: 2
      mgmt_ip: 1192.168.11.12/24
l3leaf:
  defaults:
    platform: VEOS-LAB
    virtual_router_mac_address: 00:1c:73:00:dc:01
    # VTEP VXLAN Tunnel source loopback IP for leaf switches, assigned in /32s
    # Assign range larger than total leaf switches
    vtep_loopback_ipv4_pool: 10.252.252.0/24
    loopback_ipv4_pool: 10.252.253.0/24
    # Offset must be >= number of spines
    loopback_ipv4_offset: 4
    # Point to Point Network Summary range, assigned as /31 for each
    # uplink interfaces
    # Assign range larger than total [spines * total potential leafs * 2]
    uplink_ipv4_pool: 10.252.250.0.0/24
    uplink_switches: [eps01.tripeee.zone, eps02.tripeee.zone, eps03.tripeee.zone, eps01.tripeee.zone]
    uplink_interfaces: [Ethernet1, Ethernet2, Ethernet3, Ethernet4]
    mlag_interfaces: [Ethernet7, Ethernet8]
    # mlag pair IP assignment - assign blocks - Assign range larger than
    # total spines + total leafs switches
    mlag_peer_ipv4_pool: 169.168.0.0/24
    mlag_peer_l3_ipv4_pool: 169.254.1.0/24
[... output truncated ...]
  node_groups:
    AVD_LEAF1:
      bgp_as: 65101
      nodes:
        AVD-LEAF1A:
          id: 1
          mgmt_ip: 192.168.11.13/24
          # Interface configured on SPINES to connect to this leaf
          uplink_switch_interfaces: [Ethernet1, Ethernet2, Ethernet3, Ethernet4]
        AVD-LEAF1B:
          id: 2
          mgmt_ip: 192.168.11.14/24
          # Interface configured on SPINES to connect to this leaf
          uplink_switch_interfaces: [Ethernet1, Ethernet2, Ethernet3, Ethernet4]
        AVD-LEAF2A:
          id: 1
          mgmt_ip: 192.168.11.15/24
          # Interface configured on SPINES to connect to this leaf
          uplink_switch_interfaces: [Ethernet1, Ethernet2, Ethernet3, Ethernet4]
        AVD-LEAF2B:
          id: 2
          mgmt_ip: 192.168.11.16/24
          # Interface configured on SPINES to connect to this leaf
          uplink_switch_interfaces: [Ethernet1, Ethernet2, Ethernet3, Ethernet4]
[... output truncated ...]
